### ISSUE TITLE
Game theme

### ISSUE THREAD

**Issue by arumoy-shome** [shaw-rohit/Hangman#2]
As a user, I want to be able to select a theme for the game. Once the game is started, I should be able to select a theme/category which I feel comfortable playing. Once I select a theme, the game should present a question related to this theme.

**Comment by shrutirao94** [comment]
Currently I have a basic iteration of this idea: The program randomly selects a theme for the user! Should be updated later!

**Comment by Pungent-Paws** [comment]
This was addressed in the wm-theme_and-tracking branch, but 2 out of 3 reviewers (@Pungent-Paws @arumoy-shome @shaw-rohit ) felt in hindsight that this has not much added value. After all, our SRS merely demand that a user does not know the randomly chosen word and that the user receives a hint about the word (which is available because of having a theme), which are requirements we have already met. 

So I guess we could close/ignore this issue. (Of course a few more words can be added manually to the `words` dictionary, but again, in principle the requirements have already been met)

**Comment by shrutirao94** [comment]
I am closing this issue for sake of not over complicating the matter. We are happy with the existing steup.
